version: "3.8"

services:
  app:
    image: fileupload-backend
    container_name: fileupload-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOUCE_DIVER_CLASS_NAME: ${SPRING_DATASOUCE_DIVER_CLASS_NAME}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}

      SPRING_TOKENENDPOINT: ${SPRING_TOKENENDPOINT}
      SPRING_USERINFOENDPOINT: ${SPRING_USERINFOENDPOINT}
      SPRING_FROENTENDURL: ${SPRING_FROENTENDURL}


      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}

    ports:
      - "8081:8081"

