spring.application.name=fileproject
server.port=8081







aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_S3_REGION}
#aws.s3.endpoint=${AWS_S3_ENDPOINT}
aws.s3.access-key=${AWS_S3_ACCESS_KEY}
aws.s3.secret-key=${AWS_S3_SECRET_KEY}

spring.data.redis.host=${SPRINGBOOT_REDIS_HOST}
spring.data.redis.port=${SPRINGBOOT_REDIS_PORT}
spring.data.redis.timeout=${SPRINGBOOT_REDIS_TIMEOUT}



spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}





spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URL}


spring.tokenEndPoint=${SPRING_TOKENENDPOINT}

spring.userInfoEndpoint=${SPRING_USERINFOENDPOINT}

spring.frontendUrl=${SPRING_FROENTENDURL}

app.cors.allowed-origins=${CORS_ORIGIN}