spring.application.name=fileproject
server.port=8081


#aws.s3.bucket-name=
#  #${BUCKET_NAME}
#aws.s3.region=
##${BUCKET_REGION}
#aws.access-key=
#  #${BUCKET_ACCESS_KEY}
#aws.secret-key=
#  #${BUCKET_SECRET_KEY}


#aws.s3.bucket-name=networksecuritynb
#aws.s3.region=us-east-1
#aws.s3.endpoint=http://localhost:9000
#aws.s3.access-key=admin
#aws.s3.secret-key=admin123

aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_S3_REGION}
aws.s3.endpoint=${AWS_S3_ENDPOINT}
aws.s3.access-key=${AWS_S3_ACCESS_KEY}
aws.s3.secret-key=${AWS_S3_SECRET_KEY}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional: Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


# provided here and at google site also as google check  this URL AND THE URL PROVIDED BY THE DEVELOPER

spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URL}



spring.tokenEndPoint=https://oauth2.googleapis.com/token

spring.userInfoEndpoint=https://oauth2.googleapis.com/tokeninfo?id_token=

spring.frontendUrl=https://fileupload-frontend.vercel.app/